ONO_SOURCE_STR = "5-tv.ru Abnews.ru Belta.by Business-gazeta.ru Echo.msk Fontanka Gazeta.ua Informpskov.ru Interfax Interfax.com.ua Iz Kommersant Lenta.ru Mk Newinform.com News.tut.by Obozrevatel.com Osnmedia Politros.com RT Rbc Regnum Rg Rosbalt Tass Topspb.tv Unian.net Ura.news Vesti Znaj.ua Znak"
RIMA_SOURCE_STR = "mbk-news meduza novaya polit republic"

SOURCE_SLUG_MAPPER = {
    "5-tv.ru": ["5-tv.ru"],
    "Abnews.ru": ["Abnews.ru"],
    "Belta.by": ["Belta.by"],
    "Business-gazeta.ru": ["Business-gazeta.ru"],
    "Echo.msk": ["Echo.msk"],
    "Fontanka": ["Fontanka"],
    "Gazeta.ua": ["Gazeta.ua"],
    "Informpskov.ru": ["Informpskov.ru"],
    "Interfax": ["Interfax"],
    "Interfax.com.ua": ["Interfax.com.ua"],
    "Iz": ["Iz"],
    "Kommersant": ["Kommersant"],
    "Lenta.ru": ["Lenta.ru"],
    "Mk": ["Mk"],
    "Newinform.com": ["Newinform.com"],
    "News.tut.by": ["News.tut.by"],
    "Obozrevatel.com": ["Obozrevatel.com"],
    "Osnmedia": ["Osnmedia"],
    "Politros.com": ["Politros.com"],
    "Rbc": ["Rbc"],
    "Regnum": ["Regnum"],
    "Rg": ["Rg"],
    "RT": ["RT"],
    "Rosbalt": ["Rosbalt"],
    "Tass": ["Tass"],
    "Topspb.tv": ["Topspb.tv"],
    "Tvrain": ["Tvrain"],
    "Unian.net": ["Unian", "Unian.net"],
    "Ura.news": ["Ura.news"],
    "Vesti": ["Vesti"],
    "Znaj.ua": ["Znaj.ua"],
    "Znak": ["Znak"],
    "Meduza": ["meduza"],
    "Novaya": ["novaya"],
    "Polit": ["polit"],
    "Republic": ["republic"],
    "MBK": ["mbk-news"]
}
